ClothSimulation: GLWindow Class Reference
GLWindow Class Reference
our main glwindow widget for NGL applications all drawing elements are put in this file the cloth is created, drawn in this class. it is updated in the timer function and checks for collisions between the cloth and the meshes
#include <GLWindow.h>
Public Slots
void setTimerDuration (int _v)
set the timer duration value
void setSim ()
to start simulation
void setSphereCollision (bool _mode)
method for cloth's collision with sphere
void setTableCollision (bool _mode)
method for cloth's collision with table
void setApplyWind (bool _mode)
method to set the bool for applying wind on cloth
void setClothPartNum (double _n)
method to set number of cloth particles it emits a signal once it has been creating, setting a flag to draw the cloth
void setDrawFlag ()
method to set the draw flag for drawing the cloth
void setClothWidth (double _w)
method to set cloth width
void setClothDepth (double _h)
method to set cloth depth
void applyOctree (bool _mode)
method to apply octree
void addWindMag (double _mag)
method to add wind magnitude
void setTexFileName (std::string _filename)
method to texture file from UI
Signals
void clothcreated ()
signal emitted when the cloth has been created
void resetCloth ()
signal to reset the cloth to its initila state
Public Member Functions
GLWindow (int _timer, QWidget *_parent)
Constructor for GLWindow.
~GLWindow ()
dtor
void startSimTimer ()
start the simulation timer
void stopSimTimer ()
stop the simulation timer
Public Attributes
double m_cp
variable to recieve user input for number of cloth partiles
Protected Member Functions
void initializeGL ()
The following methods must be implimented in the sub class this is called when the window is created.
void resizeGL (const int _w, const int _h)
this is called whenever the window is re-sized
void paintGL ()
this is the main gl drawing routine which is called whenever the window needs to be re-drawn
Private Member Functions
void mouseMoveEvent (QMouseEvent *_event)
this method is called every time a mouse is moved
void mousePressEvent (QMouseEvent *_event)
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
void mouseReleaseEvent (QMouseEvent *_event)
this method is called everytime the mouse button is released inherited from QObject and overridden here.
void wheelEvent (QWheelEvent *_event)
this method is called everytime the mouse wheel is moved inherited from QObject and overridden here.
void timerEvent (QTimerEvent *_event)
timer event trigered by startTimer
void loadMatricesToShader (ngl::TransformStack &_tx)
method to load the tx stack (+MVP) to the shader
void loadMatricesToColourShader (ngl::TransformStack &_tx)
method load matrices to the colour shader
void clothSphereCollision ()
method for cloth's collision with sphere
void dropOnTable ()
method to apply wind on cloth
Private Attributes
int m_timer
the timer
int m_spinXFace
used to store the x rotation mouse value
int m_spinYFace
used to store the y rotation mouse value
bool m_rotate
flag to indicate if the mouse button is pressed when dragging
bool m_translate
flag to indicate if the Right mouse button is pressed when dragging
int m_origX
the previous x mouse value
int m_origY
the previous y mouse value
int m_origXPos
the previous x mouse value for Position changes
int m_origYPos
the previous y mouse value for Position changes
ngl::Vec3 m_modelPos
the model position for mouse movement
ngl::Camera * m_cam
Our Camera.
ngl::TransformStack m_transformStack
transformation stack for the gl transformations etc
Cloth * m_cloth
pointer to Cloth
Props m_prop
meshes
int m_timerValue
the timer value in ms
ngl::Vec3 tcenter
table's coordinate: tcenter - table center; t1,t2,t3,t4 - vertices; tnormal - table normal
ngl::Vec3 t1
ngl::Vec3 t2
ngl::Vec3 t3
ngl::Vec3 t4
ngl::Vec3 tnormal
float twidth
table's width and depth
float tdepth
GLuint m_texIDTable
texture id for table and sphere;
GLuint m_texIDSphere
bool m_sim
bool m_sphereCollision
bool m_tableCollision
bool m_applyWind
bool m_draw
bool m_reset
std::string clothtex
Detailed Description
our main glwindow widget for NGL applications all drawing elements are put in this file the cloth is created, drawn in this class. it is updated in the timer function and checks for collisions between the cloth and the meshes
Definition at line 41 of file GLWindow.h.
Constructor & Destructor Documentation
GLWindow::GLWindow (int _timer, QWidget * _parent)
Constructor for GLWindow.
Parameters:
[in] _timer the time value for simulation updates
[in] _parent the parent window to create the GL context in
Definition at line 18 of file GLWindow.cpp.
References clothtex, m_cp, m_draw, m_reset, m_rotate, m_sim, m_sphereCollision, m_spinXFace, m_spinYFace, m_tableCollision, m_timerValue, and startSimTimer().
                    : QGLWidget( new CreateCoreGLContext(QGLFormat::defaultFormat()), _parent )
{
     // set this widget to have the initial keyboard focus
     setFocus();
     // re-size the widget to that of the parent (in this case the GLFrame passed in on construction)
     this->resize(_parent->size());
     // Now set the initial GLWindow attributes to default values
     // Roate is false
     m_rotate=false;
     // mouse rotation values set to 0
     m_spinXFace=0;
     m_spinYFace=0;
     m_timerValue=_timer;
     startSimTimer();
     m_sim=false;
     m_sphereCollision=false;
     m_tableCollision = false;
     m_draw = false;
     m_reset=true;
     m_cp = 10.0f;
     clothtex = "texture/table.png";
}
GLWindow::~GLWindow ()
dtor
Definition at line 45 of file GLWindow.cpp.
{
    ngl::NGLInit *init = ngl::NGLInit::instance();
    init->NGLQuit();
}
Member Function Documentation
void GLWindow::addWindMag (double _mag) [slot]
method to add wind magnitude
Definition at line 580 of file GLWindow.cpp.
References m_cloth, and Cloth::m_windMag.
{
    m_cloth->m_windMag = _mag/1000;
}
void GLWindow::applyOctree (bool _mode) [slot]
method to apply octree
Definition at line 575 of file GLWindow.cpp.
References Cloth::m_applyOctree, and m_cloth.
{
    m_cloth->m_applyOctree = _mode;
}
void GLWindow::clothcreated () [signal]
signal emitted when the cloth has been created
void GLWindow::clothSphereCollision () [private]
method for cloth's collision with sphere
Definition at line 469 of file GLWindow.cpp.
References m_cloth, and Cloth::m_massVert.
{
    for(std::vector<ngl::Vec3>::size_type i=0;i<m_cloth->m_massVert.size();++i)
       {
           //check for collisions
            ngl::Vec3 relPos;
            GLfloat len,dist,minDist;
            //sphere rad and pos
            ngl::Vec3 sPos;
            sPos.set(2,-4,1);
            minDist =1.65; //
            //cloth particle position
            ngl::Vec3 cpPos = m_cloth->m_massVert[i]->getPosition();
            //cloth particle velocity
            ngl::Vec3 cpVel = m_cloth->m_massVert[i]->getVelocity();
            relPos = (cpPos - sPos);
            //distance
            len = relPos.length();
            if(len<=minDist)
            {
                //collision response
                relPos.normalize();
                ngl::Vec3 pos = m_cloth->m_massVert[i]->getPosition();
                pos += (relPos*(minDist - len));
                m_cloth->m_massVert[i]->setPosition(pos);
                ngl::Vec3 vel = -cpVel.dot(relPos)*relPos+(cpVel-cpVel.dot(relPos)*relPos);
                m_cloth->m_massVert[i]->setVelocity(vel);
            }
         }
}
void GLWindow::dropOnTable () [private]
method to apply wind on cloth
method for cloth's collision with table
Definition at line 502 of file GLWindow.cpp.
References m_cloth, Cloth::m_massVert, t1, t2, t3, t4, tcenter, tdepth, tnormal, and twidth.
{
    twidth=6.0f;tdepth=6.0f;
    GLfloat d;
    ngl::Vec3 particlePos;
    float ext[4];
    ext[0]=ext[1]=twidth/2.0f;
    ext[2]=ext[3]=tdepth/2.0f;
    tcenter.set(5,-5,5);
    t1.set(tcenter.m_x-ext[0],tcenter.m_y,tcenter.m_z-ext[2]);
    t2.set(tcenter.m_x+ext[0],tcenter.m_y,tcenter.m_z-ext[2]);
    t3.set(tcenter.m_x-ext[0],tcenter.m_y,tcenter.m_z+ext[2]);
    t4.set(tcenter.m_x+ext[0],tcenter.m_y,tcenter.m_z+ext[2]);
    tnormal=calcNormal(t4,t3,t2);
    for(std::vector<ngl::Vec3>::size_type i=0;i<m_cloth->m_massVert.size();++i)
    {
        particlePos = m_cloth->m_massVert[i]->getPosition();
        d = tnormal.dot(particlePos);
        if(d<=tcenter.m_y)
        {
            if((particlePos.m_x>=t1.m_x && particlePos.m_x<=t2.m_x &&
                particlePos.m_z>=t1.m_z && particlePos.m_z<=t4.m_z) &&
                (particlePos.m_y<=-5) &&(particlePos.m_y>=-5.1)  )
                {
                    m_cloth->m_massVert[i]->setFixed();
                }
         }
     }
}
void GLWindow::initializeGL () [protected]
The following methods must be implimented in the sub class this is called when the window is created.
Definition at line 55 of file GLWindow.cpp.
References Props::addProp(), clothtex, m_cam, m_cloth, and m_prop.
{
glClearColor(0.4f, 0.4f, 0.4f, 1.0f);        // Grey Background
// enable depth testing for drawing
 glEnable(GL_DEPTH_TEST);
 // Now we will create a basic Camera from the graphics library
 // This is a static camera so it only needs to be set once
 // First create Values for the camera position
 //ngl::Vec3 from(0,0,20);
 ngl::Vec3 from(-10,5,30);
 ngl::Vec3 to(0,0,0);
 ngl::Vec3 up(0,1,0);
 ngl::NGLInit *Init = ngl::NGLInit::instance();
 #ifdef WIN32
  glewInit();
 #endif
 Init->initGlew();
 m_cam= new ngl::Camera(from,to,up,ngl::PERSPECTIVE);
 // set the shape using FOV 45 Aspect Ratio based on Width and Height
 // The final two are near and far clipping planes of 0.5 and 10
 m_cam->setShape(45,(float)720.0/576.0,0.5,150,ngl::PERSPECTIVE);
 // now to load the shader and set the values
 // grab an instance of shader manager
 ngl::ShaderLib *shader=ngl::ShaderLib::instance();
 // we are creating a shader called Phong
 shader->createShaderProgram("Phong");
 // now we are going to create empty shaders for Frag and Vert
 shader->attachShader("PhongVertex",ngl::VERTEX);
 shader->attachShader("PhongFragment",ngl::FRAGMENT);
 // attach the source
 shader->loadShaderSource("PhongVertex","shaders/Phong.vs");
 shader->loadShaderSource("PhongFragment","shaders/Phong.fs");
 // compile the shaders
 shader->compileShader("PhongVertex");
 shader->compileShader("PhongFragment");
 // add them to the program
 shader->attachShaderToProgram("Phong","PhongVertex");
 shader->attachShaderToProgram("Phong","PhongFragment");
 // now bind the shader attributes for most NGL primitives we use the following
 // layout attribute 0 is the vertex data (x,y,z)
 shader->bindAttribute("Phong",0,"inVert");
 // attribute 1 is the UV data u,v (if present)
 shader->bindAttribute("Phong",1,"inUV");
 // attribute 2 are the normals x,y,z
 shader->bindAttribute("Phong",2,"inNormal");
 // now we have associated this data we can link the shader
 shader->linkProgramObject("Phong");
 // and make it active ready to load values
 (*shader)["Phong"]->use();
 shader->setShaderParam1i("Normalize",1);
 //------
 // texture shader
 ngl::ShaderLib *shader1=ngl::ShaderLib::instance();
 // we are creating a shader called Texture
 shader1->createShaderProgram("Texture");
 // now we are going to create empty shaders for Frag and Vert
 shader1->attachShader("TextureVertex",ngl::VERTEX);
 shader1->attachShader("TextureFragment",ngl::FRAGMENT);
 // attach the source
 shader1->loadShaderSource("TextureVertex","shaders/TextureVertex.glsl");
 shader1->loadShaderSource("TextureFragment","shaders/TextureFragment.glsl");
 // compile the shaders
 shader1->compileShader("TextureVertex");
 shader1->compileShader("TextureFragment");
 // add them to the program
 shader1->attachShaderToProgram("Texture","TextureVertex");
 shader1->attachShaderToProgram("Texture","TextureFragment");
 // now we have associated this data we can link the shader
 shader1->linkProgramObject("Texture");
 (*shader1)["Texture"]->use();
 //------
 // now pass the modelView and projection values to the shader
 // the shader will use the currently active material and light0 so set them
 ngl::Material m(ngl::SILVER);
 m.loadToShader("material");
 ngl::Light light(ngl::Vec3(4,4,0),ngl::Colour(1,1,1,1),ngl::Colour(1,1,1,1),ngl::POINTLIGHT);
 ngl::Light spot(ngl::Vec3(10,2,2),ngl::Colour(1,1,1,1),ngl::Colour(1,1,1,1),ngl::SPOTLIGHT);
 // now create our light this is done after the camera so we can pass the
 // transpose of the projection matrix to the light to do correct eye space
 // transformations
 ngl::Mat4 iv=m_cam->getViewMatrix();
 iv.transpose();
 light.setTransform(iv);
 light.setAttenuation(1,0,0);
 light.enable();
 // load these values to the shader as well
 light.loadToShader("light");
 //SPOTLIGHT
 spot.setTransform(iv);
 spot.setAttenuation(1,0,0);
 spot.enable();
 // load these values to the shader as well
 spot.loadToShader("light");
 shader->createShaderProgram("Colour");
 shader->attachShader("ColourVertex",ngl::VERTEX);
 shader->attachShader("ColourFragment",ngl::FRAGMENT);
 shader->loadShaderSource("ColourVertex","shaders/Colour.vs");
 shader->loadShaderSource("ColourFragment","shaders/Colour.fs");
 shader->compileShader("ColourVertex");
 shader->compileShader("ColourFragment");
 shader->attachShaderToProgram("Colour","ColourVertex");
 shader->attachShaderToProgram("Colour","ColourFragment");
 shader->bindAttribute("Colour",0,"inVert");
 shader->linkProgramObject("Colour");
 //m_cloth = new Cloth("texture/table.png");
 m_cloth = new Cloth(clothtex);
 m_prop.addProp("psphere","props/sphere_1.obj","texture/silk.png");
 m_prop.addProp("ptable","props/table_1.obj","texture/wood.jpg");
 //primitive instance for draw function of sphere
 ngl::VAOPrimitives *prim =  ngl::VAOPrimitives::instance();
   prim->createSphere("sphere",1.0,40);
   ngl::Vec3 n;
   n.set(0,-1,0);
   prim->createTrianglePlane("table",1,1,1,1,n);
}
void GLWindow::loadMatricesToColourShader (ngl::TransformStack & _tx) [private]
method load matrices to the colour shader
Definition at line 230 of file GLWindow.cpp.
References m_cam.
{
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  (*shader)["Colour"]->use();
  ngl::Mat4 MV;
  ngl::Mat4 MVP;
  MV=_tx.getCurrAndGlobal().getMatrix()*m_cam->getViewMatrix() ;
  MVP=MV*m_cam->getProjectionMatrix() ;
  shader->setShaderParamFromMat4("MVP",MVP);
}
void GLWindow::loadMatricesToShader (ngl::TransformStack & _tx) [private]
method to load the tx stack (+MVP) to the shader
Parameters:
_tx the transform stack to use for the model part of the matrix
Definition at line 208 of file GLWindow.cpp.
References m_cam.
{
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  //(*shader)["Phong"]->use();
  ngl::Mat4 MV;
  ngl::Mat4 MVP;
  ngl::Mat3 normalMatrix;
  ngl::Mat4 M;
  M=_tx.getCurrentTransform().getMatrix();
  MV=_tx.getCurrAndGlobal().getMatrix()*m_cam->getViewMatrix() ;
  MVP=MV*m_cam->getProjectionMatrix();
  normalMatrix=MV;
  normalMatrix.inverse();
  shader->setShaderParamFromMat4("MV",MV);
  shader->setShaderParamFromMat4("MVP",MVP);
  shader->setShaderParamFromMat3("normalMatrix",normalMatrix);
  shader->setShaderParamFromMat4("M",M);
}
void GLWindow::mouseMoveEvent (QMouseEvent * _event) [private]
this method is called every time a mouse is moved
Parameters:
_event the Qt Event structure
Definition at line 334 of file GLWindow.cpp.
References INCREMENT, m_modelPos, m_origX, m_origXPos, m_origY, m_origYPos, m_rotate, m_spinXFace, m_spinYFace, and m_translate.
{
  // note the method buttons() is the button state when event was called
  // this is different from button() which is used to check which button was
  // pressed when the mousePress/Release event is generated
    if(m_rotate && _event->buttons() == Qt::LeftButton)
    {
      int diffx=_event->x()-m_origX;
      int diffy=_event->y()-m_origY;
      m_spinXFace += (float) 0.5f * diffy;
      m_spinYFace += (float) 0.5f * diffx;
      m_origX = _event->x();
      m_origY = _event->y();
      updateGL();
    }
    // right mouse translate code
    else if(m_translate && _event->buttons() == Qt::RightButton)
    {
      int diffX = (int)(_event->x() - m_origXPos);
      int diffY = (int)(_event->y() - m_origYPos);
      m_origXPos=_event->x();
      m_origYPos=_event->y();
      m_modelPos.m_x += INCREMENT * diffX;
      m_modelPos.m_y -= INCREMENT * diffY;
      updateGL();
    }
}
void GLWindow::mousePressEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 365 of file GLWindow.cpp.
References m_origX, m_origXPos, m_origY, m_origYPos, m_rotate, and m_translate.
{
  // this method is called when the mouse button is pressed in this case we
  // store the value where the maouse was clicked (x,y) and set the Rotate flag to true
    if(_event->button() == Qt::LeftButton)
    {
      m_origX = _event->x();
      m_origY = _event->y();
      m_rotate =true;
    }
    // right mouse translate mode
    else if(_event->button() == Qt::RightButton)
    {
      m_origXPos = _event->x();
      m_origYPos = _event->y();
      m_translate=true;
    }
}
void GLWindow::mouseReleaseEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is released inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 387 of file GLWindow.cpp.
References m_rotate, and m_translate.
{
  // this event is called when the mouse button is released
  // we then set Rotate to false
    if (_event->button() == Qt::LeftButton)
    {
      m_rotate=false;
    }
    // right mouse translate mode
    if (_event->button() == Qt::RightButton)
    {
      m_translate=false;
    }
}
void GLWindow::paintGL () [protected]
this is the main gl drawing routine which is called whenever the window needs to be re-drawn
Definition at line 248 of file GLWindow.cpp.
References Props::draw(), Cloth::drawTriCloth(), loadMatricesToShader(), m_cam, m_cloth, m_draw, Cloth::m_fix, m_modelPos, m_prop, m_sim, m_sphereCollision, m_spinXFace, m_spinYFace, m_tableCollision, m_texIDTable, and m_transformStack.
{
  // grab an instance of the shader manager
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  // clear the screen and depth buffer
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
  // Rotation based on the mouse position for our global
  // transform
  ngl::Transformation trans;
  trans.setRotation(m_spinXFace,m_spinYFace,0);
  // Rotation based on the mouse position for our global
  // transform
  ngl::Mat4 rotX;
  ngl::Mat4 rotY;
  // create the rotation matrices
  rotX.rotateX(m_spinXFace);
  rotY.rotateY(m_spinYFace);
  // multiply the rotations
  ngl::Mat4 final=rotY*rotX;
  // add the translations
  final.m_m[3][0] = m_modelPos.m_x;
  final.m_m[3][1] = m_modelPos.m_y;
  final.m_m[3][2] = m_modelPos.m_z;
  // set this in the TX stack
  trans.setMatrix(final);
  // set this in the TX stack
  m_transformStack.setGlobal(trans);
  // draw spring lines
  shader->use("Phong");
if (m_draw == true || m_sim==true)
{
    //cloth
    m_transformStack.pushTransform();
    {
        ngl::ShaderLib *shader=ngl::ShaderLib::instance();
        (*shader)["Texture"]->use();
        m_transformStack.setPosition(-5.0,0.0,0.0);
        loadMatricesToShader(m_transformStack);
        m_cloth->drawTriCloth("Texture",m_transformStack,m_cam);
    }
    m_transformStack.popTransform();
    //table
    if( m_tableCollision == true)
    {
        m_cloth->m_fix =false;
        m_transformStack.pushTransform();
        {
            ngl::ShaderLib *shader=ngl::ShaderLib::instance();
             (*shader)["Texture"]->use();
            m_transformStack.setPosition(0.0,-5.5,5.0);
            m_transformStack.setScale(5.2,6.0,5.2);
            glEnable (GL_BLEND);
            glBindTexture(GL_TEXTURE_2D,m_texIDTable);
            loadMatricesToShader(m_transformStack);
            m_prop.draw("ptable");
             glDisable(GL_BLEND);
         }
       m_transformStack.popTransform();
    }
    //sphere
    if( m_sphereCollision == true)
    {
        m_cloth->m_fix =true;
        float rad = 1.5;
        m_transformStack.pushTransform();
        {
            ngl::ShaderLib *shader=ngl::ShaderLib::instance();
             (*shader)["Texture"]->use();
            //m_transformStack.setPosition(2,-4,1);
            m_transformStack.setPosition(-3,-4,1);
            m_transformStack.setScale(rad,rad,rad);
            loadMatricesToShader(m_transformStack);
            m_prop.draw("psphere");
        }
        m_transformStack.popTransform();
    }
  }
}
void GLWindow::resetCloth () [signal]
signal to reset the cloth to its initila state
void GLWindow::resizeGL (const int _w, const int _h) [protected]
this is called whenever the window is re-sized
Parameters:
[in] _w the width of the resized window
[in] _h the height of the resized window
Definition at line 199 of file GLWindow.cpp.
References m_cam.
{
  glViewport(0,0,_w,_h);
  m_cam->setShape(45,(float)_w/_h,0.5,150,ngl::PERSPECTIVE);
}
void GLWindow::setApplyWind (bool _mode) [slot]
method to set the bool for applying wind on cloth
Returns:
bool to set wind or not
Definition at line 552 of file GLWindow.cpp.
References m_applyWind, m_cloth, Cloth::m_fix, and resetCloth().
{
    m_cloth->m_fix = true;
    emit resetCloth();
    m_applyWind = _mode;
}
void GLWindow::setClothDepth (double _h) [slot]
method to set cloth depth
Definition at line 570 of file GLWindow.cpp.
References m_cloth, and Cloth::mHeight.
{
    m_cloth->mHeight = _h;
}
void GLWindow::setClothPartNum (double _n) [slot]
method to set number of cloth particles it emits a signal once it has been creating, setting a flag to draw the cloth
Definition at line 183 of file GLWindow.cpp.
References clothcreated(), clothtex, Cloth::createCloth(), m_cloth, m_cp, Cloth::m_fix, and m_reset.
{
    m_cp = _n;
    if(m_reset==true)
    {
        m_cloth->m_fix = true;
        m_cloth->createCloth(m_cp,clothtex);
        m_reset=false;
        emit clothcreated();
    }
}
void GLWindow::setClothWidth (double _w) [slot]
method to set cloth width
Definition at line 565 of file GLWindow.cpp.
References m_cloth, and Cloth::mWidth.
{
    m_cloth->mWidth = _w;
}
void GLWindow::setDrawFlag () [slot]
method to set the draw flag for drawing the cloth
Definition at line 559 of file GLWindow.cpp.
References m_draw.
{
    m_draw = true;
    updateGL();
}
void GLWindow::setSim () [slot]
to start simulation
Definition at line 532 of file GLWindow.cpp.
References m_cp, m_sim, and setClothPartNum().
{
    m_sim = true;
    setClothPartNum(m_cp);
    updateGL();
}
void GLWindow::setSphereCollision (bool _mode) [slot]
method for cloth's collision with sphere
Definition at line 539 of file GLWindow.cpp.
References m_sphereCollision, and resetCloth().
{
    emit resetCloth();
    m_sphereCollision = _mode;
}
void GLWindow::setTableCollision (bool _mode) [slot]
method for cloth's collision with table
Definition at line 545 of file GLWindow.cpp.
References m_reset, m_tableCollision, and resetCloth().
{
    m_reset=true;
    emit resetCloth();
    m_tableCollision = _mode;
}
void GLWindow::setTexFileName (std::string _filename) [slot]
method to texture file from UI
Definition at line 585 of file GLWindow.cpp.
References clothtex.
{
    clothtex = _filename;
    updateGL();
}
void GLWindow::setTimerDuration (int _v) [inline, slot]
set the timer duration value
Parameters:
[in] _v the timer value in ms
Definition at line 85 of file GLWindow.h.
References m_timerValue.
{m_timerValue=_v;}
void GLWindow::startSimTimer ()
start the simulation timer
Definition at line 463 of file GLWindow.cpp.
References m_timer, and m_timerValue.
{
m_timer=startTimer(m_timerValue);
}
void GLWindow::stopSimTimer ()
stop the simulation timer
void GLWindow::timerEvent (QTimerEvent * _event) [private]
timer event trigered by startTimer
Definition at line 421 of file GLWindow.cpp.
References Cloth::applyWindForce(), clothSphereCollision(), dropOnTable(), m_applyWind, m_cloth, m_draw, Cloth::m_fix, Cloth::m_massVert, m_reset, m_sim, m_sphereCollision, m_tableCollision, resetCloth(), and Cloth::updateCloth().
{
    if(m_sim == true || m_draw == true)
    {
        //m_cloth->updateCloth();
        m_cloth->updateCloth();
        if(m_sphereCollision==true)
        {   clothSphereCollision(); m_reset=true;
            m_sim = false;
        }
        if(m_tableCollision==true)
            {
                emit resetCloth();
                m_reset=true;
                for(std::vector<ngl::Vec3>::size_type i=0;i<m_cloth->m_massVert.size();++i)
                {
                    m_cloth->m_massVert[i]->setNotFixed();
                    dropOnTable();
                }
                m_sim=false;
            }
        if(m_applyWind==true && m_cloth->m_fix == true)
        {
            emit resetCloth();
           m_cloth->applyWindForce();
           m_sim=false;
           updateGL();
        }
        updateGL();
    }
}
void GLWindow::wheelEvent (QWheelEvent * _event) [private]
this method is called everytime the mouse wheel is moved inherited from QObject and overridden here.
Parameters:
_event the Qt Event structure
Definition at line 406 of file GLWindow.cpp.
References m_modelPos, and ZOOM.
{
  // check the diff of the wheel position (0 means no change)
  if(_event->delta() > 0)
  {
    m_modelPos.m_z+=ZOOM;
  }
  else if(_event->delta() <0 )
  {
    m_modelPos.m_z-=ZOOM;
  }
  updateGL();
}
Member Data Documentation
std::string GLWindow::clothtex [private]
Definition at line 213 of file GLWindow.h.
bool GLWindow::m_applyWind [private]
Definition at line 210 of file GLWindow.h.
ngl::Camera* GLWindow::m_cam [private]
Our Camera.
Definition at line 177 of file GLWindow.h.
Cloth* GLWindow::m_cloth [private]
pointer to Cloth
Definition at line 185 of file GLWindow.h.
double GLWindow::m_cp
variable to recieve user input for number of cloth partiles
Definition at line 70 of file GLWindow.h.
bool GLWindow::m_draw [private]
Definition at line 211 of file GLWindow.h.
ngl::Vec3 GLWindow::m_modelPos [private]
the model position for mouse movement
Definition at line 173 of file GLWindow.h.
int GLWindow::m_origX [private]
the previous x mouse value
Definition at line 157 of file GLWindow.h.
int GLWindow::m_origXPos [private]
the previous x mouse value for Position changes
Definition at line 165 of file GLWindow.h.
int GLWindow::m_origY [private]
the previous y mouse value
Definition at line 161 of file GLWindow.h.
int GLWindow::m_origYPos [private]
the previous y mouse value for Position changes
Definition at line 169 of file GLWindow.h.
Props GLWindow::m_prop [private]
meshes
Definition at line 189 of file GLWindow.h.
bool GLWindow::m_reset [private]
Definition at line 212 of file GLWindow.h.
bool GLWindow::m_rotate [private]
flag to indicate if the mouse button is pressed when dragging
Definition at line 149 of file GLWindow.h.
bool GLWindow::m_sim [private]
Definition at line 207 of file GLWindow.h.
bool GLWindow::m_sphereCollision [private]
Definition at line 208 of file GLWindow.h.
int GLWindow::m_spinXFace [private]
used to store the x rotation mouse value
Definition at line 141 of file GLWindow.h.
int GLWindow::m_spinYFace [private]
used to store the y rotation mouse value
Definition at line 145 of file GLWindow.h.
bool GLWindow::m_tableCollision [private]
Definition at line 209 of file GLWindow.h.
GLuint GLWindow::m_texIDSphere [private]
Definition at line 205 of file GLWindow.h.
GLuint GLWindow::m_texIDTable [private]
texture id for table and sphere;
Definition at line 205 of file GLWindow.h.
int GLWindow::m_timer [private]
the timer
Definition at line 137 of file GLWindow.h.
int GLWindow::m_timerValue [private]
the timer value in ms
Definition at line 193 of file GLWindow.h.
ngl::TransformStack GLWindow::m_transformStack [private]
transformation stack for the gl transformations etc
Definition at line 181 of file GLWindow.h.
bool GLWindow::m_translate [private]
flag to indicate if the Right mouse button is pressed when dragging
Definition at line 153 of file GLWindow.h.
ngl::Vec3 GLWindow::t1 [private]
Definition at line 197 of file GLWindow.h.
ngl::Vec3 GLWindow::t2 [private]
Definition at line 197 of file GLWindow.h.
ngl::Vec3 GLWindow::t3 [private]
Definition at line 197 of file GLWindow.h.
ngl::Vec3 GLWindow::t4 [private]
Definition at line 197 of file GLWindow.h.
ngl::Vec3 GLWindow::tcenter [private]
table's coordinate: tcenter - table center; t1,t2,t3,t4 - vertices; tnormal - table normal
Definition at line 197 of file GLWindow.h.
float GLWindow::tdepth [private]
Definition at line 201 of file GLWindow.h.
ngl::Vec3 GLWindow::tnormal [private]
Definition at line 197 of file GLWindow.h.
float GLWindow::twidth [private]
table's width and depth
Definition at line 201 of file GLWindow.h.
The documentation for this class was generated from the following files:
GLWindow.h
GLWindow.cpp