ClothSimulation: ParticleOctree Class Reference
ParticleOctree Class Reference
#include <ParticleOctree.h>
Public Member Functions
ParticleOctree (int _height, BoundingBox _limit)
virtual void checkCollisionOnNode (TreeNode< ClothParticle > *node)
Detailed Description
Definition at line 8 of file ParticleOctree.h.
Constructor & Destructor Documentation
ParticleOctree::ParticleOctree (int _height, BoundingBox _limit) [inline]
Definition at line 11 of file ParticleOctree.h.
       :
       AbstractOctree <ClothParticle,ngl::Vec3> ( _height,  _limit)
     {}
Member Function Documentation
void ParticleOctree::checkCollisionOnNode (TreeNode< ClothParticle > * node) [virtual]
Implements AbstractOctree< ClothParticle, ngl::Vec3 >.
Definition at line 8 of file ParticleOctree.cpp.
References ClothParticle::getPosition(), ClothParticle::getVelocity(), and ClothParticle::setVelocity().
{
    if(node->m_height !=1)
    {
        for(int i=0;i<8;++i)
        {
            checkCollisionOnNode(node->m_child[i]);
        }
    }
    else
    {
        if(node->m_objectList.size()<=1)
        {
            return;
        }
        ngl::Vec3 P, Q, Vp, N, force;
        float Rp, Rq, dist, speed;
        BOOST_FOREACH(ClothParticle *currentParticle,node->m_objectList)
        {
            P = currentParticle->getPosition();
            Vp = currentParticle->getVelocity();
            speed = Vp.length();
            Rp = 0.1;
            //currentParticle->getRadius();
            force.m_x = force.m_y = force.m_z = 0.0;
            BOOST_FOREACH(ClothParticle *testParticle,node->m_objectList )
            {
                // no need to self test
                if(testParticle==currentParticle)
                {
                  // continue
                  continue;
                 }
                Q = testParticle->getPosition();
                Rq = 0.1;
                        //testParticle->getRadius();
                dist = Rq + Rq - (P-Q).length();
                if(dist > 0) // collision between P and Q
                {
                    N = P-Q;
                    N.normalize();
                    force += dist*N;
                }
            }
            Vp += force;
            Vp.normalize();
            currentParticle->setVelocity(force);
        }
    }
}
The documentation for this class was generated from the following files:
ParticleOctree.h
ParticleOctree.cpp