ClothSimulation: Cloth Class Reference
Cloth Class Reference
this class creates the cloth according to mass-spring model it updates the cloth with respect to the internal spring forces and the external force acting on the cloth the mass particle(connecting the springs) states are updated using the RK4 integrator
#include <Cloth.h>
Public Member Functions
Cloth ()
Constructor.
Cloth (std::string _texture)
Constructor.
~Cloth ()
basket destructor
void createCloth (double _n, std::string _texture)
method to create the cloth grid and its spring connections
void drawTriCloth (const std::string &_shaderName, ngl::TransformStack &_transformStack, ngl::Camera *_cam)
Draw method for drawing the cloth.
void updateCloth ()
method to update the cloth- forces(internal and external) and update the mass particles according to RK4 integrator state values
void applyWindForce ()
void createSpring (int _id, ClothParticle *_vertA, ClothParticle *_vertB, int _sptype)
void drawSpring (ngl::Vec3 _vertA, ngl::Vec3 _vertB, int _sptype)
void drawSpring (ClothSpring _cs)
Public Attributes
int m_horiParticles
number of horizontal mass particles
int m_vertParticles
number of vertical mass particles
float mWidth
cloth width
float mHeight
cloth height
std::vector< ClothParticle * > m_massVert
vector array for the cloth's mass particles
std::vector< ClothParticle * > m_triArray
vector array for the cloth's mass particles stored as a traingular mesh
bool m_fix
bool to keep cloth fixed for simulations
bool m_applyOctree
bool to give user the choie of applying octree
double m_windMag
wind magnitude that can be added via user interface
Private Member Functions
void collisionWithBalls ()
method to check for self collision detection between cloth mass particles to prevent penetration
void loadMatricesToShader (ngl::TransformStack &_tx, ngl::Camera *_cam) const
load all the transform values to the shader
Private Attributes
ngl::Vec3 m_gravity
forces
std::vector< massPoints > m_vertData
mass point vertices data - for drawing the triangulated cloth mesh
std::vector< ClothSpring > m_clothSpringArr
vector containg all the springs in the cloth
ClothParticle m_massVertex
vector containg all the springs in the cloth
GLuint m_textureID
cloth texture id
ParticleOctree * collisionTree
octree for collision detection
Detailed Description
this class creates the cloth according to mass-spring model it updates the cloth with respect to the internal spring forces and the external force acting on the cloth the mass particle(connecting the springs) states are updated using the RK4 integrator
his class contains all meshes required in the simulation using this class, we load meshes once which can be attached to objects in simulation
this class creates the cloth's springs creating the cloth structure and gives it the properties of streching, shear and bending
this class creates the cloth's mass particles connecting the springs together. the state of the mass particle is determined by the position and velocity calculated using the RK4 integrator
Definition at line 46 of file Cloth.h.
Constructor & Destructor Documentation
Cloth::Cloth ()
Constructor.
Definition at line 6 of file Cloth.cpp.
References m_horiParticles, m_vertParticles, mHeight, and mWidth.
            {
    m_horiParticles = 10.0f; //10 20    60
    m_vertParticles = 10.0f; //10 20    60
    mWidth = 10.0f;         //5
    mHeight = 10.0f;        //5
}
Cloth::Cloth (std::string _texture)
Constructor.
Parameters:
[in] _texture cloth texture
Definition at line 13 of file Cloth.cpp.
References collisionTree, m_applyOctree, m_horiParticles, BoundingBox::m_maxx, BoundingBox::m_maxy, BoundingBox::m_maxz, BoundingBox::m_minx, BoundingBox::m_miny, BoundingBox::m_minz, m_textureID, m_vertParticles, m_windMag, mHeight, and mWidth.
{
    m_horiParticles = 10.0f; //10 20    60
    m_vertParticles = 10.0f; //10 20    60
    mWidth = 5.0f;      //5
    mHeight = 5.0f;     //5
    //texture
    ngl::Texture tex(_texture);
    m_textureID=tex.setTextureGL();
    BoundingBox bb;
        bb.m_minx = bb.m_miny = bb.m_minz = -10.0;
        bb.m_maxx = bb.m_maxy = bb.m_maxz = 10.0;
        collisionTree = new ParticleOctree (4, bb); // control the height of the octree
        m_applyOctree = false;
    m_windMag = 0.0;
}
Cloth::~Cloth ()
basket destructor
Definition at line 33 of file Cloth.cpp.
{
    //delete m_clothSpring;
}
Member Function Documentation
void Cloth::applyWindForce ()
Definition at line 326 of file Cloth.cpp.
References m_triArray, and m_windMag.
{
    //6- wind forces
     for(std::vector<ngl::Vec3>::size_type i=0;i<m_triArray.size();i+=3)
     {
         ngl::Vec3 nor,d,direction;
         ngl::Vec3 p1 = m_triArray[i]->getPosition();
         ngl::Vec3 p2 = m_triArray[i+1]->getPosition();
         ngl::Vec3 p3 = m_triArray[i+2]->getPosition();
        // std::cout<<i<<": p1= "<<p1<<"\t p2="<<p2<<"\t p3 ="<<p3<<std::endl;
         nor = calcNormal(p1,p2,p3);
         //nor.normalize();
         //d.set((nor.normalize();));
         ngl::Vec3 wind;
         wind.set(0.001,0,-0.001);
         wind.m_x += m_windMag;
         wind.m_z += m_windMag;
         direction.set(wind);
         ngl::Vec3 f = nor*direction;
         m_triArray[i]->m_force+=f;
         m_triArray[i+1]->m_force+=f;
         m_triArray[i+2]->m_force+=f;
     }
}
void Cloth::collisionWithBalls () [private]
method to check for self collision detection between cloth mass particles to prevent penetration
Definition at line 312 of file Cloth.cpp.
References AbstractOctree< T, VEC >::addObject(), AbstractOctree< T, VEC >::checkCollision(), AbstractOctree< T, VEC >::clearTree(), collisionTree, and m_massVert.
{
    collisionTree->clearTree();
//    for(std::list<ClothParticle *>::iterator itr = m_massVert.begin(); itr!= m_massVert.end(); ++itr)
//    {
        for(std::vector<ClothParticle *>::size_type i=0;i<m_massVert.size()-1;++i)
        {
            collisionTree->addObject(m_massVert[i]);
    }
    collisionTree->checkCollision();
}
void Cloth::createCloth (double _n, std::string _texture)
method to create the cloth grid and its spring connections
Parameters:
[in] _n number of horizontal and vertical particles
Definition at line 38 of file Cloth.cpp.
References createSpring(), m_fix, m_horiParticles, m_massVert, m_textureID, m_vertParticles, mHeight, and mWidth.
{
    ngl::Texture tex(_texture);
    m_textureID=tex.setTextureGL();
    m_horiParticles = _n;
    m_vertParticles = _n;
    int id = 0;
    m_massVert.resize(m_horiParticles * m_vertParticles);
    for(int x =0;x<m_horiParticles;++x)
    {
        for(int y=0;y<m_vertParticles;++y)
        {
            ngl::Vec3 pos;
            pos.set(mWidth *(x/(float)m_horiParticles)*2,2,mHeight*(y/(float)m_vertParticles)*2);
            ngl::Vec3 vel;
            vel.set(0.0f,0.0f,0.0f);
            m_massVert.at(y*m_horiParticles+x)=new ClothParticle(pos,vel,1.0f,false);
            if(m_fix == true)
            {
                if(y==0)
                {
    //                if ((x == 0) || (x == 4) || (x == 8) || (x== m_horiParticles-9) || (x== m_horiParticles-5) || (x== m_horiParticles-1))
                      if ((x == 0) || (x == 1) || (x == 4) || (x == 5) || (x == 8) || (x == 9) ||
                          (x== m_horiParticles-10) || (x== m_horiParticles-9) || (x== m_horiParticles-6) || (x== m_horiParticles-5) || (x== m_horiParticles-2) || (x== m_horiParticles-1))
                    {
                        m_massVert.at(y*m_horiParticles+x)->m_fixed = true;
                    }
                }
            }
        }
    }
    //connections
    for(int x =0;x<m_horiParticles;++x)
    {
        for(int y=0;y<m_vertParticles;++y)
        {
            //structural
            if (x<m_horiParticles-1)
            {
                createSpring(id++,m_massVert[y*m_horiParticles+x],m_massVert[y*m_horiParticles+x +1],0);
            }
            if (y<m_vertParticles-1)
            {
                createSpring(id++,m_massVert[y*m_horiParticles+x],m_massVert[y*m_horiParticles+x +m_horiParticles],0);
            }
            //shear
            if (x<m_horiParticles-1 && y<m_vertParticles-1)
            {
                createSpring(id++,m_massVert[y*m_horiParticles+x],m_massVert[y*m_horiParticles+x +m_horiParticles+1],1);
                createSpring(id++,m_massVert[y*m_horiParticles+x+1],m_massVert[y*m_horiParticles+x +m_horiParticles],1);
            }
            //bending
            if (x<m_horiParticles-2)
            { createSpring(id++,m_massVert[y*m_horiParticles+x],m_massVert[y*m_horiParticles+x+2],2); }
            if (y<m_horiParticles-2)
            { createSpring(id++,m_massVert[y*m_horiParticles+x],m_massVert[y*m_horiParticles+x +m_horiParticles +m_horiParticles],2); }
            if (x<m_horiParticles-2 && y<m_vertParticles-2)
            {
                createSpring(id++,m_massVert[y*m_horiParticles+x],m_massVert[y*m_horiParticles+x +m_horiParticles +m_horiParticles+2],2);
                createSpring(id++,m_massVert[y*m_horiParticles+x+2],m_massVert[y*m_horiParticles+x +m_horiParticles +m_horiParticles],2);
            }
        }
    }
 }
void Cloth::createSpring (int _id, ClothParticle * _vertA, ClothParticle * _vertB, int _sptype)
Definition at line 264 of file Cloth.cpp.
References m_clothSpringArr.
{
     ClothSpring cs(_id, _vertA, _vertB, 300.0f, 3.0f,_sptype); //40 , 1.0  150,2 (300-3 stable like a light fab)
     m_clothSpringArr.push_back(cs);
}
void Cloth::drawSpring (ClothSpring _cs)
Definition at line 248 of file Cloth.cpp.
References ClothSpring::getPositionA(), and ClothSpring::getPositionB().
{
    std::vector <ngl::Vec3> points(2);
    points[0] = _cs.getPositionA();
    points[1] = _cs.getPositionB();
    ngl::VertexArrayObject *vaoSpring = ngl::VertexArrayObject::createVOA(GL_LINES);
    vaoSpring->bind();
    vaoSpring->setData(2*sizeof(ngl::Vec3),points[0].m_x);
    vaoSpring->setNumIndices(2);
    vaoSpring->setVertexAttributePointer(0,3,GL_FLOAT,0,0);
    vaoSpring->draw();
    vaoSpring->unbind();
    delete vaoSpring;
}
void Cloth::drawSpring (ngl::Vec3 _vertA, ngl::Vec3 _vertB, int _sptype)
Definition at line 232 of file Cloth.cpp.
{
    std::vector <ngl::Vec3> points(2);
    points[0] = _vertA;
    points[1] = _vertB;
    ngl::VertexArrayObject *vaoSpring = ngl::VertexArrayObject::createVOA(GL_LINES);
    vaoSpring->bind();
    vaoSpring->setData(2*sizeof(ngl::Vec3),points[0].m_x);
    vaoSpring->setNumIndices(2);
    vaoSpring->setVertexAttributePointer(0,3,GL_FLOAT,0,0);
    vaoSpring->draw();
    vaoSpring->unbind();
    delete vaoSpring;
}
void Cloth::drawTriCloth (const std::string & _shaderName, ngl::TransformStack & _transformStack, ngl::Camera * _cam)
Draw method for drawing the cloth.
Parameters:
[in] _shaderName the shader
[in] _transformStack the transformation stack
[in] _cam the camera
Definition at line 108 of file Cloth.cpp.
References loadMatricesToShader(), m_horiParticles, m_massVert, m_textureID, m_triArray, m_vertData, m_vertParticles, massPoints::nx, massPoints::ny, massPoints::nz, massPoints::u, massPoints::v, massPoints::x, massPoints::y, and massPoints::z.
{
    // texture co-ords start at 0,0
    // texture steps
    ngl::Real du=0.9/m_horiParticles;
    ngl::Real dv=0.9/m_vertParticles;
    ngl::Real u=0.0;
    ngl::Real v=0.0;
    // a std::vector to store our verts
    massPoints vert;
    for(int x =0;x<m_horiParticles-1;++x)
    {
        for(int y=0;y<m_vertParticles-1;++y)
        {
          /* tri 1
              // counter clock wise
              3
              | \
              |  \
              |   \
              1____2
              */
              // the normals are always the same so set them for d first
              ngl::Vec3 _vN =calcNormal(m_massVert[y*m_horiParticles+x]->getPosition(),m_massVert[y*m_horiParticles+x + 1]->getPosition(),m_massVert[y*m_horiParticles+x +m_horiParticles]->getPosition());
              vert.nx=_vN.m_x;
              vert.ny=_vN.m_y;
              vert.nz=_vN.m_z;
              vert.u=u; vert.v=v+dv;
              vert.x=m_massVert[y*m_horiParticles+x]->getPosition().m_x;
              vert.y=m_massVert[y*m_horiParticles+x]->getPosition().m_y;
              vert.z=m_massVert[y*m_horiParticles+x]->getPosition().m_z;
              m_triArray.push_back(m_massVert[y*m_horiParticles+x]);
              m_vertData.push_back(vert);
              // 2
              vert.u=u+du; vert.v=v+dv;
              vert.x=m_massVert[y*m_horiParticles+x + 1]->getPosition().m_x;
              vert.y=m_massVert[y*m_horiParticles+x + 1]->getPosition().m_y;
              vert.z=m_massVert[y*m_horiParticles+x + 1]->getPosition().m_z;
              m_triArray.push_back(m_massVert[y*m_horiParticles+x + 1]);
              m_vertData.push_back(vert);
              // 3
              vert.u=u; vert.v=v;
              vert.x=m_massVert[y*m_horiParticles+x +m_horiParticles]->getPosition().m_x;
              vert.y=m_massVert[y*m_horiParticles+x +m_horiParticles]->getPosition().m_y;
              vert.z=m_massVert[y*m_horiParticles+x +m_horiParticles]->getPosition().m_z;
              m_triArray.push_back(m_massVert[y*m_horiParticles+x +m_horiParticles]);
              m_vertData.push_back(vert);
          /* tri 2 w,0,d
        // counter clock wise
         3_____2
          \    |
            \  |
             \ |
              \|
              1
              */
              vert.nx=_vN.m_x;
              vert.ny=_vN.m_y;
              vert.nz=_vN.m_z;
              vert.u=u+du; vert.v=v+dv;
              vert.x=m_massVert[y*m_horiParticles+x + 1]->getPosition().m_x;
              vert.y=m_massVert[y*m_horiParticles+x + 1]->getPosition().m_y;
              vert.z=m_massVert[y*m_horiParticles+x + 1]->getPosition().m_z;
              m_triArray.push_back(m_massVert[y*m_horiParticles+x + 1]);
              m_vertData.push_back(vert);
              // 2
              vert.u=u+du; vert.v=v;
              vert.x=m_massVert[y*m_horiParticles+x + m_horiParticles +1]->getPosition().m_x;
              vert.y=m_massVert[y*m_horiParticles+x + m_horiParticles +1]->getPosition().m_y;
              vert.z=m_massVert[y*m_horiParticles+x + m_horiParticles +1]->getPosition().m_z;
              m_triArray.push_back(m_massVert[y*m_horiParticles+x + m_horiParticles +1]);
              m_vertData.push_back(vert);
              // 3
              vert.u=u; vert.v=v;
              vert.x=m_massVert[y*m_horiParticles+x + m_horiParticles]->getPosition().m_x;
              vert.y=m_massVert[y*m_horiParticles+x + m_horiParticles]->getPosition().m_y;
              vert.z=m_massVert[y*m_horiParticles+x + m_horiParticles]->getPosition().m_z;
              m_triArray.push_back(m_massVert[y*m_horiParticles+x + m_horiParticles]);
              m_vertData.push_back(vert);
            u+=du;
          } // end w loop
          u=0.0;
          v+=du;
      } // end d loop
      // now create the VBO
        ngl::ShaderLib *shader=ngl::ShaderLib::instance();
        glEnable (GL_BLEND);
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
        shader->use(_shaderName);
        ngl::VertexArrayObject *vao_tri = ngl::VertexArrayObject::createVOA(GL_TRIANGLES);
        vao_tri->bind();
        vao_tri->setData(m_vertData.size()*sizeof(massPoints),m_vertData[0].u);
        vao_tri->setVertexAttributePointer(0,3,GL_FLOAT,sizeof(massPoints),5);
        vao_tri->setVertexAttributePointer(1,2,GL_FLOAT,sizeof(massPoints),0);
        vao_tri->setVertexAttributePointer(2,3,GL_FLOAT,sizeof(massPoints),2);
        vao_tri->setNumIndices(m_vertData.size());
        glBindTexture(GL_TEXTURE_2D,m_textureID);
        loadMatricesToShader(_transformStack,_cam);
        vao_tri->draw();
        vao_tri->unbind();
    glDisable(GL_BLEND);
}
void Cloth::loadMatricesToShader (ngl::TransformStack & _tx, ngl::Camera * _cam) const [private]
load all the transform values to the shader
Parameters:
[in] _tx the current transform to load
[in] _cam the camera
Definition at line 298 of file Cloth.cpp.
{
    ngl::ShaderLib *shader=ngl::ShaderLib::instance();
    ngl::Mat4 MV;
    ngl::Mat4 MVP;
    MV=_tx.getCurrAndGlobal().getMatrix()*_cam->getViewMatrix() ;
    MVP=MV*_cam->getProjectionMatrix();
    shader->setShaderParamFromMat4("MVP",MVP);
}
void Cloth::updateCloth ()
method to update the cloth- forces(internal and external) and update the mass particles according to RK4 integrator state values
Definition at line 270 of file Cloth.cpp.
References collisionWithBalls(), m_applyOctree, m_clothSpringArr, m_massVert, and m_vertData.
{
    // 1- spring forces
    for(std::vector<ClothSpring>::size_type i=0;i<m_clothSpringArr.size();++i)
    {
        //springforces- cal forces exerted by spring on both the particles
        //store tht in the force variable of particles
        m_clothSpringArr[i].m_posA->m_force+=(m_clothSpringArr[i].calSpringForces()*-1.0);
        m_clothSpringArr[i].m_posB->m_force+=m_clothSpringArr[i].calSpringForces();
    }
    // 2 - gravity and update using RK4
    for(std::vector<ngl::Vec3>::size_type i=0;i<m_massVert.size();++i)
    {
        m_massVert[i]->applyGravity();
        m_massVert[i]->update();
        m_massVert[i]->m_force.set(0.0f,0.0f,0.0f);
    }
    //3 - self collisions
    if(m_applyOctree == true)
    {
        collisionWithBalls();
    }
    //clear the verdata for drawing
    m_vertData.clear();
}
Member Data Documentation
ParticleOctree* Cloth::collisionTree [private]
octree for collision detection
Definition at line 175 of file Cloth.h.
bool Cloth::m_applyOctree
bool to give user the choie of applying octree
Definition at line 103 of file Cloth.h.
std::vector<ClothSpring> Cloth::m_clothSpringArr [private]
vector containg all the springs in the cloth
Definition at line 160 of file Cloth.h.
bool Cloth::m_fix
bool to keep cloth fixed for simulations
Definition at line 99 of file Cloth.h.
ngl::Vec3 Cloth::m_gravity [private]
forces
Definition at line 150 of file Cloth.h.
int Cloth::m_horiParticles
number of horizontal mass particles
Definition at line 70 of file Cloth.h.
std::vector<ClothParticle*> Cloth::m_massVert
vector array for the cloth's mass particles
Definition at line 90 of file Cloth.h.
ClothParticle Cloth::m_massVertex [private]
vector containg all the springs in the cloth
Definition at line 165 of file Cloth.h.
GLuint Cloth::m_textureID [private]
cloth texture id
Definition at line 170 of file Cloth.h.
std::vector<ClothParticle*> Cloth::m_triArray
vector array for the cloth's mass particles stored as a traingular mesh
Definition at line 95 of file Cloth.h.
std::vector<massPoints> Cloth::m_vertData [private]
mass point vertices data - for drawing the triangulated cloth mesh
Definition at line 155 of file Cloth.h.
int Cloth::m_vertParticles
number of vertical mass particles
Definition at line 75 of file Cloth.h.
double Cloth::m_windMag
wind magnitude that can be added via user interface
Definition at line 107 of file Cloth.h.
float Cloth::mHeight
cloth height
Definition at line 85 of file Cloth.h.
float Cloth::mWidth
cloth width
Definition at line 80 of file Cloth.h.
The documentation for this class was generated from the following files:
Cloth.h
Cloth.cpp