ClothSimulation: AbstractRK4Integrator Class Reference
AbstractRK4Integrator Class Reference
a simple base class to do RK4 integration this class then needs the motionFunction to be implemented so we can integrate the values
#include <AbstractRK4Integrator.h>
Public Member Functions
AbstractRK4Integrator (State _state)
ctor passing in inital state
AbstractRK4Integrator ()
virtual ~AbstractRK4Integrator ()
virtual ngl::Vec3 motionFunction (const State &_state, float _t)=0
the actual function we need to implement for the integration this can be anything this is a pure virtual method an needs to be implemented in the class inheriting this
State evaluate (const State &_initial, float _t)
method to evaluate the state given initial value and time step
State evaluate (const State &_initial, float _t, float _dt, const State &_d)
method to evaluate the state given initial value and time step
void integrate (float _t, float _dt)
method to evaluate the state given initial value and time step
State getState () const
accesor to get the current state value
Protected Attributes
State m_state
the state value
Detailed Description
a simple base class to do RK4 integration this class then needs the motionFunction to be implemented so we can integrate the values
Definition at line 40 of file AbstractRK4Integrator.h.
Constructor & Destructor Documentation
AbstractRK4Integrator::AbstractRK4Integrator (State _state) [inline]
ctor passing in inital state
Parameters:
[in] _state the state to set for the initial value
Definition at line 48 of file AbstractRK4Integrator.h.
                         :
                          m_state(_state){;}
  //----------------------------------------------------------------------------------------------------------------------
AbstractRK4Integrator::AbstractRK4Integrator () [inline]
Definition at line 54 of file AbstractRK4Integrator.h.
{;}
virtual AbstractRK4Integrator::~AbstractRK4Integrator () [inline, virtual]
Definition at line 56 of file AbstractRK4Integrator.h.
{;}
Member Function Documentation
State AbstractRK4Integrator::evaluate (const State & _initial, float _t, float _dt, const State & _d)
method to evaluate the state given initial value and time step
Parameters:
[in] _initial the initial state
[in] _t the current time step value
[in] _dt the delta time step for integration
[in] _d the derivative for the integration step
Definition at line 18 of file AbstractRK4Integrator.cpp.
References State::m_position, State::m_velocity, and motionFunction().
{
  State state;
  state.m_position = _initial.m_position + _d.m_position*_dt;
  state.m_velocity = _initial.m_velocity + _d.m_velocity*_dt;
  State output;
  output.m_position = state.m_velocity;
  output.m_velocity = motionFunction(state, _t+_dt);
  return output;
}
State AbstractRK4Integrator::evaluate (const State & _initial, float _t)
method to evaluate the state given initial value and time step
Parameters:
[in] _initial the initial state
[in] _t the current time step value
Definition at line 6 of file AbstractRK4Integrator.cpp.
References State::m_position, State::m_velocity, and motionFunction().
{
  State output;
  output.m_position=_initial.m_velocity;
  output.m_velocity=motionFunction(_initial, _t);
  return output;
}
State AbstractRK4Integrator::getState () const [inline]
accesor to get the current state value
Returns:
m_state the current state value
Definition at line 105 of file AbstractRK4Integrator.h.
References m_state.
{return m_state;}
void AbstractRK4Integrator::integrate (float _t, float _dt)
method to evaluate the state given initial value and time step
Parameters:
[in] _initial the initial state
[in] _t the current time step value
[in] _dt the delta time step for integration
Definition at line 35 of file AbstractRK4Integrator.cpp.
References evaluate(), State::m_position, m_state, and State::m_velocity.
{
  // basic RK4 integration we calculate the initial value then two slopes
  // and combine together see
  // http://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_methods for more details
  State a = evaluate(m_state, _t);
  State b = evaluate(m_state, _t, _dt*0.5f, a);
  State c = evaluate(m_state, _t, _dt*0.5f, b);
  State d = evaluate(m_state, _t, _dt, c);
  const ngl::Vec3 dxdt = 1.0f/6.0f * (a.m_position + 2.0f*(b.m_position + c.m_position) + d.m_position);
  const ngl::Vec3 dvdt = 1.0f/6.0f * (a.m_velocity + 2.0f*(b.m_velocity + c.m_velocity) + d.m_velocity);
  m_state.m_position = m_state.m_position + dxdt*_dt;
  m_state.m_velocity = m_state.m_velocity + dvdt*_dt;
    //std::cout<<"\n integate val: pos="<<m_state.m_position<<" vel = "<<m_state.m_velocity;
}
virtual ngl::Vec3 AbstractRK4Integrator::motionFunction (const State & _state, float _t) [pure virtual]
the actual function we need to implement for the integration this can be anything this is a pure virtual method an needs to be implemented in the class inheriting this
Parameters:
[in] _state the state we wish to calculate the motion function for
[in] _t the current time step to integrate for
Implemented in ClothParticle.
Member Data Documentation
State AbstractRK4Integrator::m_state [protected]
the state value
Definition at line 110 of file AbstractRK4Integrator.h.
The documentation for this class was generated from the following files:
AbstractRK4Integrator.h
AbstractRK4Integrator.cpp