ClothSimulation: ClothSpring Class Reference
ClothSpring Class Reference
#include <ClothSpring.h>
Public Member Functions
ClothSpring ()
Constructor.
ClothSpring (int _id, ClothParticle *_posA, ClothParticle *_posB, float _k, float _d, int _stype)
Constructor.
int getSpringID ()
method to get spring id
ngl::Vec3 calSpringForces ()
method to calculate the spring forces F = -k(|x|-d)(x/|x|) - bv where k is the spring constant |x| is the distance between the two spring points d is the distance of seperation b is the coefficient of damping larger b increases the damping force v is the relative velocity between the spring points
ngl::Vec3 getPositionA ()
method to get the position of cloth particle at end A from the integrator
ngl::Vec3 getPositionB ()
method to get the position of cloth particle at end B from the integrator
float getRestLength ()
method to get the rest length of the spring
Public Attributes
ClothParticle * m_posA
start position of spring (a pointer to the cloth particle present at its end A)
ClothParticle * m_posB
end position of spring (a pointer to the cloth particle present at its end B)
int m_springType
type of spring
Private Attributes
float m_k
Hooke's Law spring constant.
float m_damping
damping force
float m_restLen
length of spring at rest
int m_id
spring id
Detailed Description
Definition at line 17 of file ClothSpring.h.
Constructor & Destructor Documentation
ClothSpring::ClothSpring ()
Constructor.
Definition at line 6 of file ClothSpring.cpp.
References m_damping, m_k, m_restLen, and m_springType.
{
    m_restLen = 1.0f;
    m_k = 2.0f;
    m_damping = 1.0f;
    m_springType = 0;
}
ClothSpring::ClothSpring (int _id, ClothParticle * _posA, ClothParticle * _posB, float _k, float _d, int _stype)
Constructor.
Parameters:
[in] _id spring id
[in] *_posA pointer to cloth particle position at end A
[in] *_posB pointer to cloth particle position at end B
[in] _k spring constant
[in] _d damping coefficient
[in] _stype spring type
Definition at line 14 of file ClothSpring.cpp.
References ClothParticle::getPosition(), m_damping, m_id, m_k, m_posA, m_posB, m_restLen, and m_springType.
{
    m_id   = _id;
    m_posA = _posA;
    m_posB = _posB;
    m_restLen = (m_posB->getPosition() - m_posA->getPosition()).length();
    m_k = _k;
    m_damping = _d;
    m_springType = _stype;
}
Member Function Documentation
ngl::Vec3 ClothSpring::calSpringForces ()
method to calculate the spring forces F = -k(|x|-d)(x/|x|) - bv where k is the spring constant |x| is the distance between the two spring points d is the distance of seperation b is the coefficient of damping larger b increases the damping force v is the relative velocity between the spring points
Returns:
a vector of the force calculated via the RK4 integrator
Definition at line 32 of file ClothSpring.cpp.
References ClothParticle::getPosition(), ClothParticle::getVelocity(), m_damping, m_k, m_posA, m_posB, and m_restLen.
{
    ngl::Vec3 velocity = m_posB->getVelocity() - m_posA->getVelocity();
    ngl::Vec3 distance = m_posB->getPosition() - m_posA->getPosition();
    float length = distance.length();
    return -m_k*(length-m_restLen)*(distance/length)-m_damping*velocity;
}
ngl::Vec3 ClothSpring::getPositionA () [inline]
method to get the position of cloth particle at end A from the integrator
Definition at line 72 of file ClothSpring.h.
References AbstractRK4Integrator::getState(), m_posA, and State::m_position.
{return m_posA->getState().m_position;}
ngl::Vec3 ClothSpring::getPositionB () [inline]
method to get the position of cloth particle at end B from the integrator
Definition at line 76 of file ClothSpring.h.
References AbstractRK4Integrator::getState(), m_posB, and State::m_position.
{return m_posB->getState().m_position;}
float ClothSpring::getRestLength () [inline]
method to get the rest length of the spring
Definition at line 80 of file ClothSpring.h.
References m_restLen.
{return m_restLen;}
int ClothSpring::getSpringID () [inline]
method to get spring id
Definition at line 57 of file ClothSpring.h.
References m_id.
{return m_id;}
Member Data Documentation
float ClothSpring::m_damping [private]
damping force
Definition at line 92 of file ClothSpring.h.
int ClothSpring::m_id [private]
spring id
Definition at line 100 of file ClothSpring.h.
float ClothSpring::m_k [private]
Hooke's Law spring constant.
Definition at line 88 of file ClothSpring.h.
ClothParticle* ClothSpring::m_posA
start position of spring (a pointer to the cloth particle present at its end A)
Definition at line 44 of file ClothSpring.h.
ClothParticle* ClothSpring::m_posB
end position of spring (a pointer to the cloth particle present at its end B)
Definition at line 48 of file ClothSpring.h.
float ClothSpring::m_restLen [private]
length of spring at rest
Definition at line 96 of file ClothSpring.h.
int ClothSpring::m_springType
type of spring
Definition at line 52 of file ClothSpring.h.
The documentation for this class was generated from the following files:
ClothSpring.h
ClothSpring.cpp